---
# This playbook performs a firmware update of a server group managed by HPE Compute Ops Management using a defined SPP baseline.
#
# Warning: Firmware updates other than iLO FW can require a server reboot!
#
# Note: To set schedule options during updates, you must create a schedule instead of a job, see COM-Schedule-group-firmware-update.yml
#
# Information about the HPE Greenlake for Compute Ops Management API can be found at:
# https://developer.greenlake.hpe.com/docs/greenlake/services/compute-ops/public/openapi/compute-ops-latest/overview/
#
# Preparation to run the playbooks: 
#
# - Secure your HPE Compute Ops Management credentials, using Ansible vault to encrypt them. From the root of this Ansible project on the Ansible control node, run:   
#     
#     $ ansible-vault create GLCP_US_West_credentials_encrypted.yml
#        
#     Once the password is entered, type the following content using your own API client credentials and connectivity endpoint:
#     
#      ---
#      ClientID: "xxxxxxxx-xxxx-xxx-xxx-xxxxxxxxx"
#      ClientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#      ConnectivityEndpoint: "https://<connectivity_endpoint>-api.compute.cloud.hpe.com"
#      
#     Note: To access the HPE Compute Ops Management API, you need to create your client credentials on the HPE GreenLake platform, see https://support.hpe.com/hpesc/public/docDisplay?docId=a00120892en_us&page=GUID-23E6EE78-AAB7-472C-8D16-7169938BE628.html
#
# - To run this playbook, use:
#
#   $ ansible-playbook COM-Group-firmware-update.yml --ask-vault-password 
#
#
# Author: lionel.jullien@hpe.com
# Date:   July 2022

    
#################################################################################
#        (C) Copyright 2022 Hewlett Packard Enterprise Development LP           #
#################################################################################
#                                                                               #
# Permission is hereby granted, free of charge, to any person obtaining a copy  #
# of this software and associated documentation files (the "Software"), to deal #
# in the Software without restriction, including without limitation the rights  #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     #
# copies of the Software, and to permit persons to whom the Software is         #
# furnished to do so, subject to the following conditions:                      #
#                                                                               #
# The above copyright notice and this permission notice shall be included in    #
# all copies or substantial portions of the Software.                           #
#                                                                               #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN     #
# THE SOFTWARE.                                                                 #
#                                                                               #
#################################################################################
#>

- hosts: localhost
  gather_facts: no
  vars_files:
    - GLCP_US_West_credentials_encrypted.yml    
  tasks:    

  - name: set variables
    set_fact:
      # Variables to perform the group firmware update 
      GroupName: "Production-Group"
      Baseline: "2022.03.0" 


#--------------------------------------Authentication with COM----------------------------------------------------------------------------------

  - name: Create HPE Compute Ops Management session
    uri:
      url: "https://sso.common.cloud.hpe.com/as/token.oauth2"
      method: POST
      body_format: raw
      headers:
        Content-Type: "application/x-www-form-urlencoded"
      body: "grant_type=client_credentials&client_id={{ ClientID }}&client_secret={{ ClientSecret }}"
    register: login

  # - debug: var=login

  - name: Set variable access_token for the bearer access_token
    set_fact:
      access_token: "{{ login.json.access_token }}"

  # - debug: var=access_token


#--------------------------------------Capture COM resource API versions -----------------------------------------------------------------------

  - name: Capture resource API versions from the COM API reference
    uri:
      url: "https://developer.greenlake.hpe.com/_auth/sidebar/__alternative-sidebar__-data-glcp-doc-portal-docs-greenlake-services-compute-ops-mgmt-sidebars.yaml"
      method: GET
      return_content: true
    register: data
    until: data.status == 200
    retries: 5
    delay: 5
    delegate_to: localhost

  # - debug: var=data

  - name: Set a variable for the COM API reference content
    set_fact:
      API_reference_content: "{{ data.content }}"

  # - debug: var=API_reference_content

  - name: Set a variable for items property of the COM API reference content 
    set_fact:
      items: "{{ API_reference_content | json_query(query) }}"
    vars:
      query: "items[?label=='API reference'].items"

  # - debug:
  #     msg: "{{ items[0] }}"

  - name: Set variables for each API version
    set_fact:
      API_resources_list: "{{ API_resources_list|default([]) +   [ { 'name': item.label | regex_replace('.{10}$', '') | replace('-', '_') , 'value': item.label[-7:] } ]    }}"
      "{{ (item.label | regex_replace('.{10}$', '') | replace('-', '_') ) + '_API_version' }}": "{{ item.label[-7:] }}"
    loop: "{{ items[0][1:-1] | reverse }}"
    loop_control:
      label: "Variable set: {{ (item.label | regex_replace('.{10}$', '')  | replace('-', '_')) + '_API_version' }} = {{ item.label[-7:] }}"
  # - name: Print API_resources_list variables
  #   debug:
  #       var=API_resources_list
  #       var=hostvars[inventory_hostname]


#--------------------------------------Collecting data------------------------------------------------------------------------------------------

  - name: Retrieve all firmware bundles
    uri:
      url: "{{ ConnectivityEndpoint }}/compute-ops-mgmt/{{ firmware_bundles_API_version }}/firmware-bundles"
      method: GET
      headers:
        Authorization: "Bearer {{ access_token }}"
    register: firmwarebundles

  # - debug: var=firmwarebundles

  - name: Set variable firmwarebundleID for firmware bundle "{{ Baseline }}"
    set_fact:
      firmwarebundleID:  "{{ (firmwarebundles | json_query(query) )[0] }}"     
    vars:
      query: "json.items[?releaseVersion=='{{ Baseline }}'].id"

  - debug: var=firmwarebundleID

  - name: Retrieve all groups
    uri:
      url: "{{ ConnectivityEndpoint }}/compute-ops-mgmt/{{ groups_API_version }}/groups"
      method: GET
      headers:
        Authorization: "Bearer {{ access_token }}"
    # Note: you cannot use groups as a variable name as it is a predefined variable name in Ansible
    # group_names and groups are predefined by Ansible
    register: allgroups

  # - debug: var=allgroups

  - name: Set variable groupid for {{ GroupName }}
    set_fact:
      groupid:  "{{ (allgroups | json_query(query) )[0] }}"
    vars:
      query: "json.items[?name=='{{ GroupName }}'].id"

  - debug: var=groupid

  - name: Set variable groupuri for {{ GroupName }}
    set_fact:
      groupuri:  "{{ (allgroups | json_query(query) )[0] }}"
    vars:
      query: "json.items[?name=='{{ GroupName }}'].selfUri"

  - debug: var=groupuri

  - name: Retrieve group {{ GroupName }}
    uri:
      url: "{{ ConnectivityEndpoint }}/compute-ops-mgmt/{{ groups_API_version }}/groups/{{ groupid }}"
      method: GET
      headers:
        Authorization: "Bearer {{ access_token }}"
    register: group
 
  - name: Retrieve all job templates
    uri:
      url: "{{ ConnectivityEndpoint }}/compute-ops-mgmt/{{ job_templates_API_version }}/job-templates"
      method: GET
      headers:
        Authorization: "Bearer {{ access_token }}"
    register: jobtemplates

  - name: Set variable jobtemplateuri for 'GroupFirmwareUpdate' 
    # GroupFirmwareUpdate is the template to use to initiate a group firmware update
    set_fact:
      jobtemplateuri:  "{{ (jobtemplates | json_query(query) )[0] }}"
    vars:
      query: "json.items[?name=='GroupFirmwareUpdate'].resourceUri"

  - debug: var=jobtemplateuri

  - name: Set a variable for devices part of group {{ GroupName }} for the following job to start the firmware update
    set_fact:
      devices:  "{{ group.json.devices |  map(attribute='id') | list  }}"
  
  - debug: var=devices


#--------------------------------------Start the firmware update -------------------------------------------------------------------------------

  - name: Create a job to start a firmware update
    # This job will update all servers in the defined group with the defined SPP
    # Warning: Any updates other than iLO FW require a server reboot!
    # Note: To set schedule options during updates, you must create a schedule instead of a job
    uri:
      url: "{{ ConnectivityEndpoint }}/compute-ops-mgmt/{{ jobs_API_version }}/jobs"
      method: POST
      headers:
        Authorization: "Bearer {{ access_token }}"
        Content-Type: "application/json"
      body_format: json
      body:
        jobTemplateUri: "{{ jobtemplateuri }}"
        resourceUri: "{{ groupuri }}"
        data:
          bundle_id: "{{ firmwarebundleID }}"
          # The list of devices must be provided even if they are already part of the group!
          devices: "{{ devices }}"
    register: result

  # - name: Display job creation result
  #   debug: var=result

  - name: Set a variable joburi 
    set_fact: 
      joburi: "{{ result.json.resourceUri }}"
  
  # - debug: var=joburi

  - name: Wait for the job to start or fail
    uri:
      url: "{{ ConnectivityEndpoint }}{{ joburi }}"
      method: GET
      headers:
        Authorization: "Bearer {{ access_token }}"
      return_content: true
    retries: 50
    delay: 5
    until: >
      (job1status.json.state == "RUNNING") 
      or 
      (job1status.json.state == "ERROR") 
    register: job1status

  # - debug: var=job1status

  - name: Display error message if job has failed
    debug: 
      msg: 
        - "The job has failed: {{ job1status.json.status }}"
        - "{{ job1status.json.data.state_reason_message.message_args[0].split('\n\n') }}"
    when: job1status.json.state == "ERROR"     

  - name: Wait for the update job to complete or fail
    uri:
      url: "{{ ConnectivityEndpoint }}{{ joburi }}"
      method: GET
      headers:
        Authorization: "Bearer {{ access_token }}"
    retries: 600
    delay: 5
    when: job1status.json.state != "ERROR" 
    until: jobstatus.json.state == "COMPLETE"
    register: jobstatus

  # - debug: var=jobstatus

  - name: Get the update report for the servers in the group after the update is complete
    uri:
      url: "{{ ConnectivityEndpoint }}/compute-ops-mgmt/{{ servers_API_version }}/servers/{{ item }}"
      method: GET
      headers:
        Authorization: "Bearer {{ access_token }}"
    when: job1status.json.state != "ERROR" 
    loop: "{{ devices }}"
    register: updatereport

  # - debug: var=updatereport  

  - name: Display Server update report
    debug: 
      msg: "Server={{ item.item }}, lastFirmwareUpdate={{ item.json.lastFirmwareUpdate }}"
    when: 
     - job1status.json.state != "ERROR"
     - item.json.lastFirmwareUpdate is defined
    loop: "{{ updatereport.results }}"
    # Message by default is too verbose, loop_control can be used to set an empty label  
    loop_control:
      label: ""

